#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    if [ ! -f env/build ]; then
        mkdir -p env/build
    fi

    gcc -std=c99 -pedantic-errors -fextended-identifiers -g -x c -o env/build/run main.c
}

function run() {
    if [ "-h" == $1 ] || [ "--help" == $1 ]; then
        echo "Usage: run [sub-command] file"
        echo
        echo "sub-command: One of: parse, lex"
        echo "file: Should be a C file. Assumed to be in local directory."
        echo
        return
    fi

    if [ -f env/build/run ]; then
        env/build/run "$@"
    fi
}

function debug() {
    if [ "-h" == $1 ] || [ "--help" == $1 ]; then
        echo "Usage: debug sub-command file"
        echo
        echo "sub-command: One of: parse, lex"
        echo "file: a C source file"
        echo
        return
    fi

    local debugger=`which kdbg`
    if [[ -f env/build/run ]] && [[ ! -z "$debugger" ]]; then
        $($debugger env/build/run -a "$1 $2")
    fi
}

function emacs() {
    $(which emacs) --no-init-file --no-splash --no-site-file --no-site-lisp --load env/.emacs "$@"
}
