#!/usr/bin/env bash
#-*- mode: sh -*-

export PROJECT_ROOT=$(pwd)
export PATH=$PROJECT_ROOT/env:$PATH

function build() {
    local cflags="-std=c99 -pedantic-errors -fextended-identifiers -g -x c \
                  -gdwarf-2 -g3 -Wno-format-security"

    gcc $cflags -o cparser main.c
    gcc $cflags -o test test.c
}

function debug() {
    local executable=$(cat env/executable-name)

    local debugger=`which kdbg`
    if [[ -f "env/build/$executable" ]] && [[ ! -z "$debugger" ]]; then
        if [[ "" == "$@" ]]; then
            $($debugger "env/build/$executable")
        else
            $($debugger "env/build/$executable" -a "$1 $2")
        fi
    fi
}

function emacs() {
    $(which emacs) --no-init-file --no-splash --no-site-file --no-site-lisp --load env/.emacs "$@"
}
